### ISSUE TITLE
App mockups

### ISSUE THREAD

**Issue by WERUreo** [cforlando/orlando-walking-tours-ios#52]

**Comment by sbaldini** [comment]
Hey @WERUreo  - any way we can get all the MVP features in a document? I'm not sure what we settled on or if there's something that's been added since our meeting.

**Comment by WERUreo** [comment]
Yeah, I'm working on that now.  I'll create a new issue and post a link when I've got it put together.

**Comment by sbaldini** [comment]
Working on user flows right now.

**Comment by sbaldini** [comment]
Wireframe pretty much complete now, working on doing some research/inspiration for branding and UI.

**Comment by WERUreo** [comment]
Just gonna add the link to the wireframe [here](https://invis.io/WN7KGPF6F).
