### ISSUE TITLE
Do we want to use MagicalRecord?

### ISSUE THREAD

**Issue by WERUreo** [cforlando/orlando-walking-tours-ios#57]
MagicalRecord is a 3rd party framework that was made to make working with Core Data a little easier.  It was used on the old Objective-C version of this project.  Do we want to continue using MagicalRecord in the new version of this project, or use vanilla Core Data?  Or is there some other 3rd party framework we could use?

**Comment by kayteecannon** [comment]
I would prefer to use regular Core Data, but I have never used MagicalRecord and I am open to learning new things.

**Comment by akozlik** [comment]
I vote yes on MagicalRecord. All MR does is abstract core data onto a more easily understandable set of APIs.

**Comment by WERUreo** [comment]
I agree with @akozlik and, in the interest of moving the project along, I'm going to go ahead and say we use [MagicalRecord](https://github.com/magicalpanda/MagicalRecord).  There is documentation on their Github page, and we have code examples in the old Objective-C version of this project we can use as reference.
