### ISSUE TITLE
Should we remove S.E Waters Grocery/Coca-Cola Sign from the list of locations?

### ISSUE THREAD

**Issue by WERUreo** [cforlando/orlando-walking-tours-ios#61]
I was doing some research on the S.E. Waters Grocery/Coca-Cola Sign.  It is one of the historic locations in our list.  I wasn't able to find it when I went on my photo-taking excursion, and it turns out that the store and sign were both demolished in 2004.

The store/sign were located at 71 E. Church St.  Supposedly, there is a plaque somewhere around there commemorating the sign (which was an Orlando Historic Landmark since 1998).

Should we remove this location from our list?  Since the sign isn't there (and apparently I can't seem to find any photos online of the sign before it was demolished), there isn't anything to see at that location.  However, if there is a plaque there, perhaps we'd like to keep it on the list so people can see the plaque?  Maybe we can even find a photo of the old sign to include in the app?

**Comment by devdupont** [comment]
If the plaque exists (verify), it should still be included as it’s on the registry. Should probably have placeholder image saying “Historical image not yet found"

**Comment by WERUreo** [comment]
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=8&cad=rja&uact=8&ved=0ahUKEwi-96yjk8vMAhUJMSYKHVIxCK0QFghEMAc&url=http%3A%2F%2Fedocs.ci.orlando.fl.us%2Fasv%2Fpaperlessagenda.nsf%2F6acecff5f30ecb0d85256bd0005abae0%2F6c01dfbca3a308648525798000513752%2F%24FILE%2FHPB%2520-%2520JAN%25202012%2520Minutes.pdf&usg=AFQjCNGlL2bVdBYjpfmL-cBxlylWHaQcsw&sig2=AzwqxXNKFJSBuXymvK0E1g

**Comment by akozlik** [comment]
I could see us going either way on this. On the one hand it would be good to have some sort of record the sign existed, even if you can't visit it. On the other, what's the point of listing it in a walking tours app if you can't visit it. Regarding what @flyinactor91 said, I'd be inclined to agree. Let's keep it in the list but make it clear that the sign has been demolished.

**Comment by WERUreo** [comment]
I like the idea of leaving locations like this on the list with a note that they have been demolished.  Tinker Field would probably be another one to fall into this category.

**Comment by akozlik** [comment]
Apparently admin access to the data portal was granted to my old work e-mail. Iv'e contacted CFA to see if they can elevate my personal account to admin status. Once that's done I can make any necessary changes to the datasets.

**Comment by WERUreo** [comment]
Sounds good.  I opened another issue (#60) to try and fill out the missing data.  There's also a couple of location coordinates that I need to correct.

**Comment by WERUreo** [comment]
Alright, so we will leave S.E. Waters Grocery/Coca-Cola Sign in the list, along with other historic locations that may no longer be around (i.e. Tinker Field).  We'll note that the landmark is no longer there (probably a good idea to make this status prominent in the list itself to alert users that if they select this location as part of their tour, they probably won't see anything).
